// <auto-generated />
using System;
using ATM_Project_InAsp.NetCoreWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ATM_Project_InAsp.NetCoreWebAPI.Migrations
{
    [DbContext(typeof(Account_Db))]
    [Migration("20241219065622_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ATM_Project_InAsp.NetCoreWebAPI.Models.DocumentDomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ATM_Project_InAsp.NetCoreWebAPI.Models.UserDomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentAddress")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentDomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDomainId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ATM_Project_InAsp.NetCoreWebAPI.Models.UserDomainModel", b =>
                {
                    b.HasOne("ATM_Project_InAsp.NetCoreWebAPI.Models.DocumentDomainModel", "DocumentDomain")
                        .WithMany()
                        .HasForeignKey("DocumentDomainId");

                    b.Navigation("DocumentDomain");
                });
#pragma warning restore 612, 618
        }
    }
}
